#!/usr/bin/env python
'''Encrypt keystore and save it to a file.

Usage:
  kestore-load
  kestore-load (-h | --help)
  kestore-load --version

Options:
  -h | --help                   Display this message.
  --version                     Display version.
'''
from docopt import docopt
from keystore import save

arguments = docopt(__doc__, version='0.2.0')
save.save('~/.keystorerc')
