#!/usr/bin/env python3
'''Decrypt keystore and write them out.

If specified, keys will be written to `directory` instead of its original path.
This is useful if you are migrating keys to a machine with a different user name
or an operating system.

Usage:
  kestore-load [--copy-to directory]
  kestore-load (-h | --help)
  kestore-load --version

Options:
  --copy-to directory           Write keys to this directory.
  -h --help                     Display this message.
  --version                     Display version.
'''

from docopt import docopt
from keystore import load, __version__

arguments = docopt(__doc__, version=__version__)
load.load('~/.keystorerc', copyto=arguments['--copy-to'])
