#!/usr/bin/env python3
'''Encrypt keystore and save it to a file.

Usage:
  kestore-load
  kestore-load (-h | --help)
  kestore-load --version

Options:
  -h --help                     Display this message.
  --version                     Display version.
'''
from docopt import docopt
from keystore import save, __version__

arguments = docopt(__doc__, version=__version__)
save.save('~/.keystorerc')
